version: '3.2'

services:
  db:
    container_name: database_imaginamos_test
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes: 
      - pg_data:/var/lib/postgresql/data
    tty: true
    ports:
      - "5432:5432"
  web:
    container_name: app_imaginamos_test
    build:
      context: .
      dockerfile: web.dockerfile
    env_file: ./.env.local
    depends_on:
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
      - 127.0.0.1:9223:9223
    environment:
      - HOST_DB=database_imaginamos_test
    command: npm run start
  migration:
    build:
      context: .
      dockerfile: web.dockerfile
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:5432",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - db
    depends_on:
      - db
    env_file: ./.env.local
    environment:
      - HOST_DB=database_imaginamos_test
volumes:
  pg_data: null