-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 16:30:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imaginamos_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imaginamos_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imaginamos_db` DEFAULT CHARACTER SET utf8 ;
USE `imaginamos_db` ;

-- -----------------------------------------------------
-- Table `imaginamos_db`.`technicians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imaginamos_db`.`technicians` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imaginamos_db`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imaginamos_db`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `technicians_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `fk_tickets_technicians_idx` (`technicians_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_technicians`
    FOREIGN KEY (`technicians_id`)
    REFERENCES `imaginamos_db`.`technicians` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
